[package]
name = "foworker_service"
version = "0.1.0"
edition = "2021"
authors = ["Jakub Mrowicki <jakub.mrowicki@sgs.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filetime = "0.2.15"